export const GalleryInfo = [
    {
        name: "one",
        dir: "./images/",
        alt: "top down picture of tools sitting on workbench",
        slug: "/projects/test-project-1",
        ariaLabel: "Link to test project 1",
        created: 1657885566,
    },
    {
        name: "two",
        dir: "./images/",
        alt: "top down picture of tools sitting on workbench",
        slug: "/projects/test-project-1",
        ariaLabel: "Link to test project 1",
        created: 1657885567,
    },
    {
        name: "three",
        dir: "./images/",
        alt: "top down picture of tools sitting on workbench",
        slug: "/projects/test-project-1",
        ariaLabel: "Link to test project 1",
        created: 1657885568,
    },
    {
        name: "four",
        dir: "./images/",
        alt: "top down picture of tools sitting on workbench",
        slug: "/projects/test-project-1",
        ariaLabel: "Link to test project 1",
        created: 1657885556,
    },
    {
        name: "five",
        dir: "./images/",
        alt: "top down picture of tools sitting on workbench",
        slug: "/projects/test-project-1",
        ariaLabel: "Link to test project 1",
        created: 1657885572,
    },
    {
        name: "six",
        dir: "./images/",
        alt: "top down picture of tools sitting on workbench",
        slug: "/projects/test-project-1",
        ariaLabel: "Link to test project 1",
        created: 1657885569,
    },
];
